version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7
    platform: linux/amd64  

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: board_db
      MYSQL_ROOT_HOST: '%'
      
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  db-data:
